plugins {
    id 'net.fabricmc.fabric-loom-remap' version '1.15.5' apply false
    id 'net.neoforged.moddev' version '2.0.141' apply false
}

allprojects {
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile).tap {
            configureEach {
                options.compilerArgs << "-Xmaxerrs" << "1000"
            }
        }
    }
}

def getAppVersion = { ->
    def declaredVersion = rootProject.findProperty('version') ?: '1.0.0'
    return declaredVersion
} as Object

allprojects {
    version = getAppVersion()
}
