pluginManagement {
    repositories {
        maven {
            name = 'JitPack'
            url = 'https://jitpack.io'
        }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Architectury'
            url = "https://maven.architectury.dev/"
        }
        maven {
            name = 'Forge'
            url = "https://files.minecraftforge.net/maven/"
        }
        gradlePluginPortal()
    }

    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'architectury-plugin') {
                useModule('com.github.Mikulasz12.architectury-plugin:architectury-plugin.gradle.plugin:e3d53cc')
            }
        }
    }
}

include('common')
include('fabric')
include('quilt')
include('forge')

enableFeaturePreview("NO_IMPLICIT_LOOKUP_IN_PARENT_PROJECTS")

rootProject.name = 'minecraft-comes-alive'
