plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

dependencies {
    compileOnly 'org.spongepowered:mixin:0.8.5'
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

def commonResourcesOutput = layout.buildDirectory.dir('commonResources')

tasks.register('prepareCommonResources', Sync) {
    from(sourceSets.main.resources)
    into(commonResourcesOutput)
    duplicatesStrategy = DuplicatesStrategy.FAIL
}

tasks.named('sourcesJar') {
    dependsOn(':fabric:runDatagen')
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources(commonResourcesOutput) {
        builtBy tasks.named('prepareCommonResources')
    }
}
