name: Java CI with Gradle

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GRADLE_OPTS: --enable-native-access=ALL-UNNAMED
      MODRINTH_TOKEN: ${{ secrets.MR_API_TOKEN }}
      CURSEFORGE_TOKEN: ${{ secrets.CF_API_TOKEN }}
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
      NO_COLOR: 1
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: false
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Build Artifacts with Gradle
        run: ./gradlew build --build-cache --configuration-cache --console=plain --non-interactive
      - name: Publish to Maven
        run: ./gradlew publish --build-cache --configuration-cache --console=plain --non-interactive
      - name: Get tag
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        id: tag
        uses: dawidd6/action-get-tag@v1
      - uses: jungwinter/split@v2
        id: split
        with:
          separator: "+"
          msg: ${{steps.tag.outputs.tag}}
      - name: "Upload to Distributors"
        uses: Kir-Antipov/mc-publish@v3.3.0
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        with:
          modrinth-id: 1W98a849
          modrinth-token: ${{ env.MODRINTH_TOKEN }}
          curseforge-id: 535291
          curseforge-token: ${{ env.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          name: "[Universal ${{steps.split.outputs._1}}] MCA Reborn - ${{steps.split.outputs._0}}"
          changelog-file: changelog.md
          version-type: ${{ contains(steps.split.outputs._0, 'beta') && 'beta' || contains(steps.split.outputs._0, 'alpha') && 'alpha' || 'release' }}
          files: build/libs/*-@(universal).jar
          loaders: |
            fabric
            forge
            quilt
          game-versions: |
            ${{steps.split.outputs._1}}
          java: |
            Java 17
          dependencies: |
            architectury-api | depends | *
            fabric-api | recommends | *
            qsl | recommends | *

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: skip
